export const STR = {
  title: "Paper Tuss",
  score: "Score",
  best: "Best",
  mainMenu: "Main Menu",
  play: "Play",
  nextLevel: "Next Level",
  gameOver: "Game Over!",
  youScored: "You scored",
  points: "points",
  throwsLeft: "Throws left",
  tapToStart: "Drag & release to toss!",
  wind: "Wind",
  level: "Level",
  basket: "Basket!",
  miss: "Miss!",
  restart: "Restart",
  menuReturn: "Return to Menu",
  throws: "throws",
};
