export const STR = {
  title: "Paper Tuss",
  score: "Score",
  best: "Best",
  mainMenu: "Main Menu",
  play: "Play",
  nextLevel: "Next Level",
  gameOver: "GAME OVER",
  youScored: "You scored",
  points: "points",
  throwsLeft: "Throws left",
  tapToStart: "Drag & release to toss!",
  wind: "Wind",
  level: "Level",
  basket: "BASKET!",
  miss: "Miss!",
  combo: "Combo",
  levelUp: "Level Up!",
  newBest: "New Best!",
  restart: "Restart",
  menuReturn: "Return to Menu",
  throws: "Throws",
};
